title: the psyquantic corner
# logo: /assets/img/yy.png
# description: >
#   unstructured collection of thoughts and ideas
show_downloads: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
